"""fixed models

Revision ID: 23cf9b2f2cc0
Revises: dc3de02473f2
Create Date: 2024-01-26 22:10:21.703743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23cf9b2f2cc0"
down_revision: Union[str, None] = "dc3de02473f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("status", sa.Integer(), nullable=False))
    op.add_column(
        "notes", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "revisions", sa.Column("created_by", sa.Integer(), nullable=False)
    )
    op.add_column(
        "revisions", sa.Column("passed", sa.Boolean(), nullable=False)
    )
    op.create_foreign_key(None, "revisions", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "revisions", type_="foreignkey")
    op.drop_column("revisions", "passed")
    op.drop_column("revisions", "created_by")
    op.drop_column("notes", "is_deleted")
    op.drop_column("notes", "status")
    # ### end Alembic commands ###
