"""added password field to user model

Revision ID: a5735603bcc5
Revises: 23cf9b2f2cc0
Create Date: 2024-01-26 22:22:56.017428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5735603bcc5"
down_revision: Union[str, None] = "23cf9b2f2cc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("encrypted_password", sa.String(), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["encrypted_password"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "encrypted_password")
    # ### end Alembic commands ###
