"""changed relation between note and revision to one to one

Revision ID: 0c744c13812f
Revises: 1706f079d564
Create Date: 2024-01-30 17:15:25.149195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c744c13812f"
down_revision: Union[str, None] = "1706f079d564"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "revisions", ["note_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "revisions", type_="unique")
    # ### end Alembic commands ###
