"""xd


Revision ID: 77c8c21512b7
Revises: 9dd11876f20a
Create Date: 2024-02-01 23:10:43.571246

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77c8c21512b7"
down_revision: Union[str, None] = "9dd11876f20a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes", sa.Column("created_by", sa.Integer(), nullable=False)
    )
    op.drop_constraint("notes_user_id_fkey", "notes", type_="foreignkey")
    op.create_foreign_key(None, "notes", "users", ["created_by"], ["id"])
    op.drop_column("notes", "user_id")
    op.drop_column("notes", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes",
        sa.Column("status", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "notes",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_foreign_key(
        "notes_user_id_fkey", "notes", "users", ["user_id"], ["id"]
    )
    op.drop_column("notes", "created_by")
    # ### end Alembic commands ###
