"""Changed user model. Now middle name is not required to create User

Revision ID: f22d1578d31d
Revises: a5735603bcc5
Create Date: 2024-01-27 15:25:00.263605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f22d1578d31d"
down_revision: Union[str, None] = "a5735603bcc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "middle_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "middle_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
